# Generated by Django 4.2.5 on 2023-09-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='existencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
